### PR TITLE
Badges

### PR DESCRIPTION
**Pull request by thibaultduponchelle**
Success: 
badgesuccess

Failed: 
badgefailed

Running:
badgerunning

Implements #12

### CODE REVIEW

**Comment by thibaultduponchelle** [comment]
Second commit prepares also for #31

**Comment by melezhik** [comment]
cool! I'll take a look later.

**Comment by melezhik** [comment]
@thibaultduponchelle  could we also have a badge for "Not started" ?

**Comment by thibaultduponchelle** [comment]
I don't know why, but I can't include it with `<img src=` in page "builds" or "projects", something seems missing

**Comment by thibaultduponchelle** [comment]
Set content type to image/svg fixed the issue.

With recent commit, badges are used by sparky ui (instead buttons) :

Screenshot from 2021-01-11 10-17-16

**Comment by melezhik** [comment]
Great! I am merging it and will test how it looks like ... Thanks for good work @thibaultduponchelle

**Comment by melezhik** [comment]
@thibaultduponchelle  I decided to remove http calls to `/badge/project/$project/` from recent builds and projects and replaced them by original implementation. My concerns:

* we might have a lot of http calls through these pages
* I like the idea of badge , but for external users not for Sparky UI itself, images can't not be changed when we change bulma css theme, and I like the idea, that with the original approach "success/running/failed" labels are automatically changed  when we change a theme ...  

Sorry, I was hurry to accept the request and should have looked at the before 😕   . But the part of PR with badges functionality is ok and it's merged,  I am just going to update Readme about this functionality ...

**Comment by thibaultduponchelle** [comment]
No problem, it's perfectly OK for me like this, badges for external, buttons (and no http calls) for internal :+1: 
And this is what I implemented first.

Thank you for having merged this :)

**Comment by melezhik** [comment]
yeah, sure! I am going to test badges once I have some projects that I test with Sparky ... And I am going to announce in raku irc as well.

**Comment by melezhik** [comment]
It works - https://github.com/melezhik/rakudist-teddy-bear/blob/master/README.md#build-status , though have a bit different appearance 😄  I don't see Sparky in the image ...

**Comment by thibaultduponchelle** [comment]
First, this is great to see it used "in real life" :grinning: 

Then : 
1. I can put back the Sparky since we now target external only.
2. The right borders a slightly truncated, I don't know why
3. The text is not centered :cry: (for instance on safari)

**Comment by melezhik** [comment]
yeah, we can do it through a new PR. Please do if you have anything already implemented ...

**Comment by thibaultduponchelle** [comment]
I made a PR for 1.
The 2. is not very important, but 3. has to be fixed, I tried to play with svg text options, but yet I don't have the solution

**Pull request merged**
